---
- hosts: root-ensemble
  vars: 
      remote_path: "{{ lookup('env', 'FABRIC8_ANSIBLE_REMOTE_PATH') }}"
      fabric8_name: "{{ lookup('env', 'FABRIC8_ANSIBLE_NAME')  }}"
  remote_user: cloud-user
  sudo: yes
  tasks:
      
  - name: Remove fabric8 chkconfig service
    command: chdir={{ remote_path}} {{ item }}
    with_items:
      - /sbin/service fabric8-service stop
      - /sbin/chkconfig fabric8-service --del
      - /bin/rm /etc/init.d/fabric8-service
    ignore_errors: yes

  - name: Stop Fabric8
    command: chdir={{ remote_path }} {{ item }}
    with_items:
      - /sbin/runuser -l fabric8 -c "/usr/bin/jps -l | /bin/grep karaf | /bin/cut -d ' ' -f 1 | /usr/bin/xargs -n1 /bin/kill -kill"
    ignore_errors: yes

  - name: Remove Fabric8
    command: /bin/rm -fr "{{ remote_path }}/{{ fabric8_name }}"
    

    

