---
# This playbook preps a set of servers for JBoss Fuse 
# and installs fuse on the ensemble servers
#
#

- name: apply common configs to all nodes
  hosts: all
  sudo: yes
  user: cloud-user

  roles:
    - fabric8-common


- name: provision fuse onto root ensemble server
  hosts: root-ensemble
  sudo: yes
  user: cloud-user
 
  roles:
    - fabric8-root-ensemble
    
- name: patch Fabric8
  hosts: root-ensemble
  sudo: yes
  user: cloud-user

